spring:
  datasource:
    url: jdbc:h2:mem:vending-machine
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
   console:
    enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update


      hibernate:
        dialect=org:
          hibernate:
            dialect:
              H2Dialect:

  application:
    name: vending-machine-api



cache-manager:
 caffeine-caches:
   - cache-names: [ProductCache, CashCache]
     spec: initialCapacity=50,maximumSize=10,expireAfterAccess=300s

