spring:
  datasource:
    url: jdbc:h2:mem:vending-machine
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
   console:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update

      hibernate:
        dialect=org:
          hibernate:
            dialect:
              H2Dialect:

  application:
    name: vending-machine-api



cache-manager:
 caffeine-caches:
   - cache-names: [ProductCache, CashCache]
     spec: initialCapacity=50,maximumSize=10,expireAfterAccess=300s

